default:
  golem_name: urgenceAviR
  golem_version: 0.0.1
  app_prod: false
  datasets_folder: null
  file_upload: false

production:
  app_prod: true
  datasets_folder: null
  file_upload: true

dev:
  golem_wd: !expr golem::pkg_path()
  datasets_folder: null
  file_upload: true
